//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсач.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllAboutClientView
    {
        public int ClientId { get; set; }
        public string CLientLN { get; set; }
        public string ClientFN { get; set; }
        public string ClientPatronomic { get; set; }
        public Nullable<bool> ClientGender { get; set; }
        public Nullable<System.DateTime> ClientHB { get; set; }
        public string ClientAddress { get; set; }
        public string ClientPhone { get; set; }
        public string ClientSnils { get; set; }
        public string ClientWorkPlaceAndPost { get; set; }
        public string ClientBloodGroup { get; set; }
        public Nullable<bool> ClientRh_ { get; set; }
        public string Allergy { get; set; }
        public string Email { get; set; }
        public string Busyness { get; set; }
        public string Education { get; set; }
        public string Position { get; set; }
        public string InsuranceName { get; set; }
        public string PassportSeria { get; set; }
        public string PassportNumber { get; set; }
        public string PassportWho { get; set; }
        public System.DateTime PassportDate { get; set; }
        public string PolisSeries { get; set; }
        public string PolisNumber { get; set; }
    }
}
