//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсач.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int ClientId { get; set; }
        public System.DateTime CardDateStart { get; set; }
        public Nullable<System.DateTime> CardDateEnd { get; set; }
        public string DesiaseId { get; set; }
        public int WorkerId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Desiase Desiase { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
