//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсач.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Card()
        {
            this.CardTablePart = new HashSet<CardTablePart>();
        }
    
        public int ID { get; set; }
        public int ClientId { get; set; }
        public System.DateTime CardDateStart { get; set; }
        public Nullable<System.DateTime> CardDateEnd { get; set; }
        public string DesiaseId { get; set; }
        public int WorkerId { get; set; }
        public string ClientComplaints { get; set; }
        public string ClientAnamnesis { get; set; }
        public string ClientObjectiveData { get; set; }
        public string ClientHarders { get; set; }
        public string ClientReason { get; set; }
        public Nullable<bool> ClientLook { get; set; }
        public string ClientHealthGroup { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Desiase Desiase { get; set; }
        public virtual Worker Worker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CardTablePart> CardTablePart { get; set; }
    }
}
