//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсач.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Card = new HashSet<Card>();
            this.Document = new HashSet<Document>();
            this.Guardian = new HashSet<Guardian>();
            this.Approval = new HashSet<Approval>();
            this.InvalidGroup = new HashSet<InvalidGroup>();
        }
    
        public int ClientId { get; set; }
        public string InsuranceId { get; set; }
        public int FamilyPositionId { get; set; }
        public int EducationId { get; set; }
        public int BusynessId { get; set; }
        public string ClientLN { get; set; }
        public string ClientFN { get; set; }
        public string ClientPatronomic { get; set; }
        public Nullable<bool> ClientGender { get; set; }
        public Nullable<System.DateTime> ClientHB { get; set; }
        public string ClientAddress { get; set; }
        public string ClientPhone { get; set; }
        public string ClientSnils { get; set; }
        public string ClientWorkPlaceAndPost { get; set; }
        public string ClientBloodGroup { get; set; }
        public Nullable<bool> ClientRh_ { get; set; }
        public string Allergy { get; set; }
        public string Email { get; set; }
    
        public virtual Benefits Benefits { get; set; }
        public virtual Busyness Busyness { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Card> Card { get; set; }
        public virtual Education Education { get; set; }
        public virtual FamilyPosition FamilyPosition { get; set; }
        public virtual Insurance Insurance { get; set; }
        public virtual ClientRequsites ClientRequsites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Document { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guardian> Guardian { get; set; }
        public virtual Passport Passport { get; set; }
        public virtual Polis Polis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Approval> Approval { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvalidGroup> InvalidGroup { get; set; }
    }
}
