//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсач.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guardian
    {
        public string GuardianFullName { get; set; }
        public int ClientId { get; set; }
        public string GuardianAddress { get; set; }
        public string GuardianPhone { get; set; }
        public int GuardianId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual GuardianPassport GuardianPassport { get; set; }
    }
}
