//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсач.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invalid
    {
        public int ClientId { get; set; }
        public int IGId { get; set; }
        public Nullable<System.DateTime> InvalidDate { get; set; }
        public Nullable<bool> InvalidFirst { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual InvalidGroup InvalidGroup { get; set; }
    }
}
