//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсач.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int PriceId { get; set; }
        public Nullable<decimal> PriceSize { get; set; }
        public Nullable<System.DateTime> PriceDate { get; set; }
        public int ServiceId { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
